# Generated by Django 4.1 on 2023-01-31 08:42

from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_post_image_alter_post_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='user_profile.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=user_profile.models.profile_avatars_directory),
        ),
    ]
